name: Test worker
on: [push]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['7.2', '7.4', '8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pcntl
          tools: composer:v2
      - name: Install composer dependencies
        run: composer install
      - name: Check example
        run: php example/worker.php